apiVersion: v1
kind: Service
metadata:
  name: simpledotnetapp-service
spec:
  selector:
    app: simpledotnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
